<a href="https://colab.research.google.com/github/Satyanarayana-vasamsetti/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [ ]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
# to saw dimensions we need to use ndim
# how many square brackets we put it increases the dimensions of array
# []-> 1 dimensioin , [[]]->two dimenstion , [[[]]]->three dimension
arr.ndim

1

In [ ]:
arr = np.array([[[[[[]]]]]])
arr.ndim
arr.shape


(1, 1, 1, 1, 1, 0)

In [ ]:
arrang = np.arange(0,10) #arange(start,stop,step)
arrang

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.linspace(0,1,5) #linspace(start,stop,number of values)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
arr = np.logspace(1,2,2) #logarthmic scale of array
arr

array([ 10., 100.])

In [ ]:
arr = np.zeros([4,4]) #default it gives float value
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr = np.ones([3,3],dtype=int)
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
arr = np.full([3,3],9)
arr

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [ ]:
arr = np.empty([2,3])
arr

array([[1.20451179e-315, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
arr = np.random.rand(5) # we have to pass how many random numbers we need
arr #generate random values between 0 and 1

array([0.95308574, 0.42831231, 0.82907668, 0.76226659, 0.12010094])

In [ ]:
arr = np.random.randn(5)
arr #random numbers based on normal distribution

array([-0.62865995, -2.14916056,  0.06427597, -0.01730836,  2.98714814])

In [ ]:
arr = np.random.randint(0,10,size=(2,3))
arr

array([[1, 7, 7],
       [5, 7, 0]])

### **NumPy DataTypes and Typecasting**

In [ ]:
arr = np.array([12,3])
arr.dtype

dtype('int64')

In [ ]:
arr = np.array([1,2.2,3])
arr.dtype

dtype('float64')

In [ ]:
new_arr = arr.astype(np.int64)
new_arr

array([1, 2, 3])

In [ ]:
arr = np.array(["satya"])
arr

array(['satya'], dtype='<U5')

In [ ]:
new_arr = arr.astype(np.int64)
new_arr #typecasting error because we can't convert it into integer

ValueError: invalid literal for int() with base 10: np.str_('satya')

In [ ]:
arr = np.array([1,2,3])
arr.itemsize

8

## **Array Reshaping**

In [ ]:
# reshape -> it can change dimensions of a array
arr = np.array([1,2,3,4,5,6])
new_arr = arr.reshape(2,3)
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
new_arr = arr.reshape(3,2)
new_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# ravel() is used to convert array into 1D array
r = new_arr.ravel()
r
r[0]=100
r
new_arr
# ravel() can change original array when we try to change ravel() array

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [ ]:
# flatten it is also used to covert array into 1D arrya, but it make copy of arrya
# if you can change value of flatten it can't effect on original arrya
flat = new_arr.flatten()
flat
flat[0]=1
flat
# new_arr

array([1, 2, 3, 4, 5, 6])

## **Arthimetic Operations on Arrays**

In [ ]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a**b)



[5 5 5 5]
[-3 -1  1  3]
[4 6 6 4]
[0.25       0.66666667 1.5        4.        ]
[0 0 1 4]
[1 8 9 4]


In [3]:
 arr = np.array([1,2,3,4])
 print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.        ]


In [4]:
print(np.exp(arr))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [6]:
angles = np.array([0,np.pi,np.pi/2])
print(np.sin(angles))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


In [7]:
arr = np.array([10,20,30,40,50])
arr[ : :2]

array([10, 30, 50])

In [8]:
arr = np.array([1,2,3,4,5])
ind = [2,4]
print(np.take(arr,ind))



[3 5]


In [11]:
# nditer get only values at index
for i in np.nditer(arr):
  print(i,end = " ")

1 2 3 4 5 

In [13]:
# where as ndenumerator gives you values along with indexs
for ind,val in np.ndenumerate(arr):
  print(ind,val)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [14]:
# Views vs Copies
# View can change value even  it is original
arr = np.array([1,2,3,4,5])
view  = arr.view()
view[0] = 100
print(view)
print(arr)


[100   2   3   4   5]
[100   2   3   4   5]


In [15]:
# copy() can't change original arr
arr = np.array([1,2,3,4,5])
copy  = arr.copy()
copy[0] = 100
print(copy)
print(arr)


[100   2   3   4   5]
[1 2 3 4 5]


In [16]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [17]:
print(arr.transpose())

[[1 3]
 [2 4]]


In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [21]:
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [22]:
print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [23]:
print(np.stack((a,b),axis = 0)) #horizontal if axis = 0

[[1 2 3]
 [4 5 6]]


In [24]:
print(np.stack((a,b),axis = 1)) #vertical if axis = 1

[[1 4]
 [2 5]
 [3 6]]


In [25]:
arr = np.array([[1,2],[3,4],[4,5],[6,7]])
arr

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [27]:
print(np.split(arr,4))

[array([[1, 2]]), array([[3, 4]]), array([[4, 5]]), array([[6, 7]])]


In [29]:
print(np.hsplit(arr,2))

[array([[1],
       [3],
       [4],
       [6]]), array([[2],
       [4],
       [5],
       [7]])]


In [30]:
print(np.vsplit(arr,2))

[array([[1, 2],
       [3, 4]]), array([[4, 5],
       [6, 7]])]


In [32]:
print(np.split(arr,2,axis = 0))#vertical split
print(np.split(arr,2,axis = 1))#horizontal split


[array([[1, 2],
       [3, 4]]), array([[4, 5],
       [6, 7]])]
[array([[1],
       [3],
       [4],
       [6]]), array([[2],
       [4],
       [5],
       [7]])]


In [34]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [36]:
print(np.repeat(arr,3))

[1 1 1 2 2 2 3 3 3 4 4 4]


In [37]:
print(np.tile(arr,3))

[1 2 3 4 1 2 3 4 1 2 3 4]


In [43]:
# The below are the aggregation functions of numpy
arr = np.array([1,2,3,4,5])
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.sum(arr))
print(np.var(arr))
print(np.average(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))


1
5
3.0
3.0
1.4142135623730951
15
2.0
3.0
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [47]:
result =  np.where(arr>5, "low","high")
result

array(['high', 'high', 'high', 'high', 'high'], dtype='<U4')

In [49]:
res = np.argwhere(arr>3)
res

array([[3],
       [4]])