<a href="https://colab.research.google.com/github/Satyanarayana-vasamsetti/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


In [5]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
# to saw dimensions we need to use ndim
# how many square brackets we put it increases the dimensions of array
# []-> 1 dimensioin , [[]]->two dimenstion , [[[]]]->three dimension
arr.ndim

1

In [7]:
arr = np.array([[[[[[]]]]]])
arr.ndim
arr.shape


(1, 1, 1, 1, 1, 0)

In [10]:
arrang = np.arange(0,10) #arange(start,stop,step)
arrang

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr = np.linspace(0,1,5) #linspace(start,stop,number of values)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
arr = np.logspace(1,2,2) #logarthmic scale of array
arr

array([ 10., 100.])

In [19]:
arr = np.zeros([4,4]) #default it gives float value
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
arr = np.ones([3,3],dtype=int)
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
arr = np.full([3,3],9)
arr

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [26]:
arr = np.empty([2,3])
arr

array([[1.20451179e-315, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [27]:
arr = np.random.rand(5) # we have to pass how many random numbers we need
arr #generate random values between 0 and 1

array([0.95308574, 0.42831231, 0.82907668, 0.76226659, 0.12010094])

In [30]:
arr = np.random.randn(5)
arr #random numbers based on normal distribution

array([-0.62865995, -2.14916056,  0.06427597, -0.01730836,  2.98714814])

In [32]:
arr = np.random.randint(0,10,size=(2,3))
arr

array([[1, 7, 7],
       [5, 7, 0]])

### **NumPy DataTypes and Typecasting**

In [33]:
arr = np.array([12,3])
arr.dtype

dtype('int64')

In [34]:
arr = np.array([1,2.2,3])
arr.dtype

dtype('float64')

In [36]:
new_arr = arr.astype(np.int64)
new_arr

array([1, 2, 3])

In [37]:
arr = np.array(["satya"])
arr

array(['satya'], dtype='<U5')

In [38]:
new_arr = arr.astype(np.int64)
new_arr #typecasting error because we can't convert it into integer

ValueError: invalid literal for int() with base 10: np.str_('satya')

In [39]:
arr = np.array([1,2,3])
arr.itemsize

8

## **Array Reshaping**

In [40]:
# reshape -> it can change dimensions of a array
arr = np.array([1,2,3,4,5,6])
new_arr = arr.reshape(2,3)
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
new_arr = arr.reshape(3,2)
new_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
# ravel() is used to convert array into 1D array
r = new_arr.ravel()
r
r[0]=100
r
new_arr
# ravel() can change original array when we try to change ravel() array

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [51]:
# flatten it is also used to covert array into 1D arrya, but it make copy of arrya
# if you can change value of flatten it can't effect on original arrya
flat = new_arr.flatten()
flat
flat[0]=1
flat
# new_arr

array([1, 2, 3, 4, 5, 6])

## **Arthimetic Operations on Arrays**

In [8]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a**b)



[5 5 5 5]
[-3 -1  1  3]
[4 6 6 4]
[0.25       0.66666667 1.5        4.        ]
[0 0 1 4]
[1 8 9 4]
